[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set laststatus=2
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build= 'make'

[[plugins]]
repo = 'Shougo/vimshell'
depends = 'vimproc.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'deris/vim-gothrough-jk'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
  let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': ['ruby'] }
  let g:syntastic_ruby_checkers = ['rubocop']
'''
